// Generated by CoffeeScript 1.7.1
'use strict';
$('#now-playing-media .bar-value').attr('title', $('#now-playing-media .bar-value').text());

API.on(API.DJ_ADVANCE, function(obj) {
  $('#now-playing-media .bar-value').attr('title', $('#now-playing-media .bar-value').text());
  if ((obj.dj != null) && obj.dj.username === API.getUser().username) {
    return window.postMessage('plugmixer_user_playing', '*');
  }
});

window.postMessage({
  about: 'plugmixer_user_info',
  userId: API.getUser().id
}, '*');

window.addEventListener('message', function(event) {
  if ((event.data.about != null) && event.data.about === 'plugmixer_send_chat') {
    return API.chatLog(event.data.message);
  }
});
