// Generated by CoffeeScript 1.6.3
(function() {
  chrome.runtime.onMessage.addListener(function(message, sender, sendResponseTo) {
    console.log(Date.now());
    return chrome.pageAction.show(sender.tab.id);
  });

}).call(this);
