// Generated by CoffeeScript 1.7.1
'use strict';
var inject;

inject = document.createElement('script');

inject.src = chrome.extension.getURL('mix.js');

(document.head || document.documentElement).appendChild(inject);

chrome.runtime.sendMessage("plugmixer_inactive_icon");

window.addEventListener("message", function(event) {
  if (event.source !== window) {
    return;
  }
  if (event.data.method) {
    switch (event.data.method) {
      case 'plugmixer_save_playlists':
        return chrome.storage.sync.set({
          'playlists': event.data.playlists
        });
      case 'plugmixer_status_change':
        chrome.storage.sync.set({
          'status': event.data.status
        });
        if (event.data.status) {
          return chrome.runtime.sendMessage("plugmixer_active_icon");
        } else {
          return chrome.runtime.sendMessage("plugmixer_inactive_icon");
        }
        break;
      case 'plugmixer_load_request':
        return chrome.storage.sync.get(['playlists', 'status'], function(data) {
          return window.postMessage({
            method: 'plugmixer_load_response',
            playlists: data['playlists'],
            status: data['status']
          }, '*');
        });
    }
  }
});
