// Generated by CoffeeScript 1.7.1
'use strict';
var inject;

inject = document.createElement('script');

inject.src = chrome.extension.getURL('mix.js');

(document.head || document.documentElement).appendChild(inject);

window.addEventListener("message", function(event) {
  if (event.source !== window) {
    return;
  }
  if (event.data.method) {
    if (event.data.method === 'save') {
      return chrome.storage.sync.set({
        'playlists': event.data.playlists
      });
    } else if (event.data.method === 'load') {
      return chrome.storage.sync.get('playlists', function(data) {
        return window.postMessage({
          method: 'load_response',
          load: data
        }, '*');
      });
    }
  }
});
