// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var inject;

  inject = document.createElement('script');

  inject.src = chrome.extension.getURL('mix.js');

  (document.head || document.documentElement).appendChild(inject);

  window.addEventListener("message", function(event) {
    if (event.source !== window) {
      return;
    }
    if (event.data.method) {
      if (event.data.method === 'save') {
        console.log('...saving playlists');
        console.log(event.data.playlists);
        return chrome.storage.sync.set({
          'playlists': event.data.playlists
        });
      } else if (event.data.method === 'load') {
        return chrome.storage.sync.get('playlists', function(data) {
          console.log('...loading playlists');
          return window.postMessage({
            method: 'load_response',
            load: data
          }, '*');
        });
      }
    }
  });

}).call(this);
