// Generated by CoffeeScript 1.7.1
var Mixer, mixer;

Mixer = (function() {
  function Mixer() {}

  Mixer.prototype.playlists = null;

  Mixer.prototype.reset = function() {
    var playlist, _i, _len, _ref, _results;
    $('#plugmixer').remove();
    API.off(API.DJ_ADVANCE, null);
    _ref = this.playlists;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      playlist = _ref[_i];
      playlist.dom.children('span.count').off("click", this.togglePlaylistStatus);
      _results.push(playlist.dom.fadeTo(0.3, 1));
    }
    return _results;
  };

  Mixer.prototype.displayLabel = function() {
    var mixerDisplay;
    mixerDisplay = '<div id="plugmixer" style="position: absolute; right: 16px; bottom: 4px;"> <span style="color: #90ad2f; font-size: 12px">PLUGMIXER</span> </div>';
    return $('#room').append(mixerDisplay);
  };

  Mixer.prototype.selectedPlaylist = function() {
    var playlist, _i, _len, _ref;
    _ref = this.playlists;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      playlist = _ref[_i];
      if (playlist.dom.children('div.activate-button').css('display') === "block") {
        return playlist;
      }
    }
    return null;
  };

  Mixer.prototype.addTriggers = function() {
    var playlist, _i, _len, _ref, _results;
    _ref = this.playlists;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      playlist = _ref[_i];
      _results.push(playlist.dom.children('span.count').click(playlist, this.togglePlaylistStatus));
    }
    return _results;
  };

  Mixer.prototype.togglePlaylistStatus = function(event) {
    var playlist;
    playlist = event.data;
    playlist.active = !playlist.active;
    if (playlist.active) {
      console.log('Activated ' + playlist.name + '.');
      return playlist.dom.fadeTo(0.3, 1);
    } else {
      console.log('Deactivated ' + playlist.name + '.');
      return playlist.dom.fadeTo(0.3, 0.4);
    }
  };

  Mixer.prototype.activate = function() {
    var _this;
    _this = this;
    console.log('Mixing of playlists initialized!');
    this.loadPlaylists();
    this.addTriggers();
    this.displayLabel();
    return API.on(API.DJ_ADVANCE, function(obj) {
      if (obj.dj.username === API.getUser().username) {
        return _this.selectRandomPlaylist();
      }
    });
  };

  Mixer.prototype.selectPlaylist = function(playlist) {
    playlist.dom.trigger("mouseup");
    $('.activate-button').click();
    console.log('Next playing from ' + playlist.name + '.');
    API.chatLog('Next playing from ' + playlist.name + '.');
    return playlist;
  };

  Mixer.prototype.active = function(index) {
    return this.active;
  };

  Mixer.prototype.selectRandomPlaylist = function() {
    var countSum, playlist, playlistCount, weightedSelect, _i, _j, _len, _len1, _ref, _ref1;
    countSum = 0;
    _ref = this.playlists.filter(this.active);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      playlist = _ref[_i];
      countSum += playlist.count;
    }
    playlistCount = this.playlists.length;
    weightedSelect = Math.floor(Math.random() * countSum) + 1;
    _ref1 = this.playlists.filter(this.active);
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      playlist = _ref1[_j];
      if (weightedSelect < playlist.count) {
        return this.selectPlaylist(playlist);
      }
      weightedSelect -= playlist.count;
    }
    return null;
  };

  Mixer.prototype.loadPlaylists = function() {
    var playlistsDom;
    playlistsDom = $('#playlist-menu div.row');
    return this.playlists = playlistsDom.map(function(i, pDom) {
      var pJq;
      pJq = $(pDom);
      return {
        name: pJq.children('span.name').text(),
        count: parseInt(pJq.children('span.count').text()),
        active: true,
        dom: pJq
      };
    });
  };

  return Mixer;

})();

if (typeof mixer !== 'undefined') {
  mixer.reset();
}

mixer = new Mixer;

mixer.activate();
