// Generated by CoffeeScript 1.7.1
'use strict';
var OPACITY, SHIFT_LEFT, tabId;

OPACITY = '0.3';

SHIFT_LEFT = '-63px';

tabId = null;

chrome.tabs.query({
  active: true,
  currentWindow: true
}, function(tabs) {
  tabId = tabs[0].id;
  return chrome.pageAction.getTitle({
    tabId: tabId
  }, function(result) {
    if (result === 'Plugmixer') {
      $('.toggle').css('left', SHIFT_LEFT);
      return $('.inactive').css('opacity', OPACITY);
    } else {
      return $('.active').css('opacity', OPACITY);
    }
  });
});

$('#status').click(function(event) {
  return chrome.tabs.sendMessage(tabId, 'plugmixer_toggle_status', function(response) {
    if (response === 'plugmixer_make_active') {
      $('.inactive').animate({
        'opacity': OPACITY,
        'left': SHIFT_LEFT
      });
      return $('.active').animate({
        'opacity': '1',
        'left': SHIFT_LEFT
      });
    } else {
      $('.inactive').animate({
        'opacity': '1',
        'left': '0'
      });
      return $('.active').animate({
        'opacity': OPACITY,
        'left': '0'
      });
    }
  });
});
