// Generated by CoffeeScript 1.7.1
'use strict';
var tabId;

tabId = null;

chrome.tabs.query({
  active: true,
  currentWindow: true
}, function(tabs) {
  tabId = tabs[0].id;
  return chrome.pageAction.getTitle({
    tabId: tabId
  }, function(result) {
    if (result === 'Plugmixer') {
      $('.toggle').css('left', '-60px');
      $('.inactive').css('opacity', '0.5');
      return $('.active').css('opacity', '1');
    } else {
      $('.toggle').css('left', '0');
      $('.active').css('opacity', '0.5');
      return $('.inactive').css('opacity', '1');
    }
  });
});

$('#status').click(function(event) {
  return chrome.tabs.sendMessage(tabId, 'plugmixer_toggle_status', function(response) {
    console.log(response);
    if (response === 'plugmixer_make_active') {
      $('.inactive').animate({
        'opacity': '0.5',
        'left': '-60px'
      });
      return $('.active').animate({
        'opacity': '1',
        'left': '-60px'
      });
    } else {
      $('.inactive').animate({
        'opacity': '1',
        'left': '0'
      });
      return $('.active').animate({
        'opacity': '0.5',
        'left': '0'
      });
    }
  });
});
